const D=window.VIREO_DATA||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stars=n=>{n=Math.max(0,Math.min(5,Number(n)||0));return '★'.repeat(n)+'☆'.repeat(5-n)};
const allPeaks=[...(D.wainwrights||[]),...(D.munros||[]),...(D.welsh||[]),...(D.peaks||[])];
const store={
 get(k,f){try{return JSON.parse(localStorage.getItem('vireo_'+k))??f}catch{return f}},
 set(k,v){try{localStorage.setItem('vireo_'+k,JSON.stringify(v))}catch{}}
};
let favourites=store.get('favourites',[]);
let logged=store.get('logged',[]);
function toast(msg){let t=document.querySelector('#vireo-toast');if(!t){t=document.createElement('div');t.id='vireo-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window._vt);window._vt=setTimeout(()=>t.classList.remove('show'),2200)}
function imgFallback(img){img.style.display='none';const p=img.parentElement;if(p)p.classList.add('image-fallback')}
function safeImage(url,alt=''){return `<div class="media-frame"><img src="${esc(url||'')}" alt="${esc(alt)}" loading="lazy" onerror="imgFallback(this)"><div class="media-fallback-mark">VIREO</div></div>`}
function isFav(name){return favourites.includes(name)}
function toggleFavourite(name){if(isFav(name))favourites=favourites.filter(x=>x!==name);else favourites.push(name);store.set('favourites',favourites);toast(isFav(name)?`${name} added to your Vireo collection`:`${name} removed from your collection`);refreshFavButtons();updatePassport()}
function toggleLogged(name){if(logged.includes(name))logged=logged.filter(x=>x!==name);else logged.push(name);store.set('logged',logged);toast(logged.includes(name)?`${name} logged to your Vireo Passport`:`${name} removed from your Passport`);refreshFavButtons();updatePassport()}
function refreshFavButtons(){document.querySelectorAll('[data-fav]').forEach(b=>{const n=b.dataset.fav;b.classList.toggle('saved',isFav(n));b.textContent=isFav(n)?'✓ SAVED':'＋ SAVE'});document.querySelectorAll('[data-log]').forEach(b=>{const n=b.dataset.log;b.classList.toggle('saved',logged.includes(n));b.textContent=logged.includes(n)?'✓ LOGGED':'＋ LOG ADVENTURE'})}
function profileData(x,label){const kind=x.kind||x.type||'Summit';const area=x.region||x.area||({Munro:'Scotland',Wainwright:'Lake District','Welsh 3000':'Eryri / Wales','Peak District':'Peak District'}[kind]||'Britain');const effort=x.difficulty==='Hard'?'Demanding':x.difficulty==='Moderate'?'Steady':'Accessible';const terrain=x.difficulty==='Hard'?'Rougher ground, steeper climbing and conditions that can change quickly.':x.difficulty==='Moderate'?'Mixed mountain ground with sustained ascent and a little more planning.':'Generally approachable terrain, though weather and ground conditions still matter.';return {kind,area,effort,terrain}}
function openProfileByName(name){const x=allPeaks.find(z=>z.name===name);if(x)openProfile(x,x.kind||x.type||'VIREO')}
function openProfile(x,label){
 const d=document.querySelector('#drawer');if(!d)return;const p=profileData(x,label);const fav=isFav(x.name),log=logged.includes(x.name);
 d.querySelector('.drawer-panel').innerHTML=`<button class="close" onclick="closeDrawer()">CLOSE ×</button><div class="drawer-top"><div><p class="kicker">${esc(label)}</p><h2>${esc(x.name)}</h2><div class="drawer-sub">${esc(p.area)} · ${esc(p.kind)}</div></div><div class="drawer-height">${esc(x.height)}<small>METRES</small></div></div><div class="meta"><span class="difficulty ${String(x.difficulty).toLowerCase()}">${esc(x.difficulty)}</span><span class="stars" title="${x.views}/5">${stars(x.views)}</span><span>${esc(p.effort)} day</span></div><div class="drawer-actions"><button data-fav="${esc(x.name)}" class="action-btn ${fav?'saved':''}" onclick="toggleFavourite(${JSON.stringify(x.name)})">${fav?'✓ SAVED':'＋ SAVE'}</button><button data-log="${esc(x.name)}" class="action-btn ${log?'saved':''}" onclick="toggleLogged(${JSON.stringify(x.name)})">${log?'✓ LOGGED':'＋ LOG ADVENTURE'}</button><button class="action-btn" onclick="sharePeak(${JSON.stringify(x.name)})">↗ SHARE</button></div><div class="profile-tabs"><button class="active" data-tab="overview">OVERVIEW</button><button data-tab="field">FIELD NOTES</button><button data-tab="plan">PLAN AHEAD</button></div><div class="profile-tab-content" id="profile-tab-content"><div class="profile-lead"><p>${esc(x.description)}</p></div><div class="info-grid"><div><span>HEIGHT</span><b>${esc(x.height)}m</b></div><div><span>VIEW RATING</span><b>${stars(x.views)}</b></div><div><span>DIFFICULTY</span><b>${esc(x.difficulty)}</b></div><div><span>AREA</span><b>${esc(p.area)}</b></div></div><div class="info-block"><span class="kicker">WHY GO</span><h3>Worth the effort</h3><p>${esc(x.whyVisit||x.description)}</p><div class="destination-more">${(x.goodFor||[]).map(z=>`<span>${esc(z)}</span>`).join('')}</div></div></div>`;
 d.classList.add('open');
 d.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchProfileTab(b.dataset.tab,x,p));
 refreshFavButtons();
}
function switchProfileTab(tab,x,p){const el=document.querySelector('#profile-tab-content');if(!el)return;document.querySelectorAll('.profile-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='overview'){el.innerHTML=`<div class="profile-lead"><p>${esc(x.description)}</p></div><div class="info-grid"><div><span>HEIGHT</span><b>${esc(x.height)}m</b></div><div><span>VIEW RATING</span><b>${stars(x.views)}</b></div><div><span>DIFFICULTY</span><b>${esc(x.difficulty)}</b></div><div><span>AREA</span><b>${esc(p.area)}</b></div></div><div class="info-block"><span class="kicker">WHY GO</span><h3>Worth the effort</h3><p>${esc(x.whyVisit||x.description)}</p><div class="destination-more">${(x.goodFor||[]).map(z=>`<span>${esc(z)}</span>`).join('')}</div></div>`}else if(tab==='field'){el.innerHTML=`<div class="info-block"><span class="kicker">VIREO FIELD NOTES</span><h3>Read the landscape</h3><p>${esc(x.fieldNote||p.terrain)}</p></div><div class="info-grid"><div><span>FEEL</span><b>${esc(p.effort)}</b></div><div><span>VIEW</span><b>${stars(x.views)}</b></div><div><span>COLLECTION</span><b>${esc(p.kind)}</b></div><div><span>STATUS</span><b>VIREO LISTED</b></div></div>`}else{el.innerHTML=`<div class="info-block"><span class="kicker">PLAN AHEAD</span><h3>More information is coming</h3><p>Vireo is building this profile out into a practical planning page. Exact routes, parking, coordinates, current weather, route distance, ascent and local facilities will be added here as the platform grows.</p></div><div class="coming-grid compact"><div class="coming-card"><b>📍 LOCATION</b><span>Information coming soon</span></div><div class="coming-card"><b>🅿️ PARKING</b><span>Information coming soon</span></div><div class="coming-card"><b>🥾 ROUTE</b><span>Information coming soon</span></div><div class="coming-card"><b>🌦️ WEATHER</b><span>Information coming soon</span></div></div>`}}
function closeDrawer(){document.querySelector('#drawer')?.classList.remove('open')}
async function sharePeak(name){const url=new URL(location.href);url.hash='peak='+encodeURIComponent(name);try{await navigator.clipboard.writeText(url.href);toast('Vireo profile link copied')}catch{toast('Profile ready to share')}}
function renderDirectory(items,o){const g=document.querySelector(o.grid),s=document.querySelector(o.search),sort=document.querySelector(o.sort),c=document.querySelector(o.count);if(!g)return;let q='',m='height',diff='all',region='all';function paint(){let a=items.filter(x=>(!q||x.name.toLowerCase().includes(q)||String(x.region||'').toLowerCase().includes(q))&& (diff==='all'||x.difficulty===diff) && (region==='all'||x.region===region));if(m==='alpha')a.sort((x,y)=>x.name.localeCompare(y.name));else if(m==='low')a.sort((x,y)=>x.height-y.height);else if(m==='views')a.sort((x,y)=>y.views-x.views);else a.sort((x,y)=>y.height-x.height);c.textContent=`${a.length} of ${items.length} shown · ${favourites.length} saved · ${logged.length} logged`;g.innerHTML=a.map(x=>`<article class="peak-card-wrap"><button class="peak-card" data-name="${esc(x.name)}"><span class="rank">${x.height}m</span><span class="peak-name">${esc(x.name)}</span><span class="peak-height">${esc(x.difficulty)} · ${stars(x.views)}</span><span class="peak-arrow">↗</span></button><button class="card-save ${isFav(x.name)?'saved':''}" data-fav="${esc(x.name)}" onclick="event.stopPropagation();toggleFavourite(${JSON.stringify(x.name)})">${isFav(x.name)?'✓ SAVED':'＋ SAVE'}</button></article>`).join('');[...g.querySelectorAll('.peak-card')].forEach(e=>e.onclick=()=>{const x=items.find(z=>z.name===e.dataset.name);if(x)openProfile(x,o.label)});refreshFavButtons()}s?.addEventListener('input',e=>{q=e.target.value.toLowerCase();paint()});sort?.addEventListener('change',e=>{m=e.target.value;paint()});document.querySelectorAll('[data-difficulty-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-difficulty-filter]').forEach(z=>z.classList.remove('active'));b.classList.add('active');diff=b.dataset.difficultyFilter;paint()});paint();window._vireoDirectoryPaint=paint}
function addDirectoryControls(){const t=document.querySelector('.directory-tools');if(!t||document.querySelector('.filter-row'))return;t.insertAdjacentHTML('afterend',`<div class="filter-row"><button class="filter active" data-difficulty-filter="all">ALL</button><button class="filter" data-difficulty-filter="Easy">EASY</button><button class="filter" data-difficulty-filter="Moderate">MODERATE</button><button class="filter" data-difficulty-filter="Hard">HARD</button><button class="filter" data-difficulty-filter="all" onclick="document.querySelector('#search').value='';document.querySelector('#sort').value='height';document.querySelector('[data-difficulty-filter=all]').click()">RESET</button></div>`)}
function renderDestinations(){const g=document.querySelector('#destinations-grid');if(!g)return;g.innerHTML=(D.destinations||[]).map(x=>`<article class="destination-card"><div class="destination-image">${safeImage(x.image,x.name)}<span>${esc(x.tag)}</span></div><div class="destination-copy"><span class="pill">${esc(x.tag)}</span><h3>${esc(x.name)}</h3><small>${esc(x.area)}</small><p>${esc(x.desc)}</p><div class="destination-more"><span>📸 PHOTOGRAPHY</span><span>📍 LOCATION</span><span>🅿️ PARKING</span></div><div class="coming-label">${esc(x.imageStatus||'INFORMATION COMING SOON')}</div><button class="text-btn" onclick="openDestination(${JSON.stringify(x.name)})">EXPLORE PLACE →</button></div></article>`).join('')}
function openDestination(name){const x=(D.destinations||[]).find(z=>z.name===name);if(!x)return;const d=document.querySelector('#drawer');if(!d)return;d.querySelector('.drawer-panel').innerHTML=`<button class="close" onclick="closeDrawer()">CLOSE ×</button><p class="kicker">PLACES WORTH GOING · ${esc(x.tag)}</p><h2>${esc(x.name)}</h2><p class="drawer-sub">${esc(x.area)}</p><div class="destination-drawer-image">${safeImage(x.image,x.name)}</div><p class="profile-description">${esc(x.desc)}</p><div class="coming-grid compact"><div class="coming-card"><b>📍 LOCATION</b><span>Information coming soon</span></div><div class="coming-card"><b>🅿️ PARKING</b><span>Information coming soon</span></div><div class="coming-card"><b>🥾 WALKS</b><span>Information coming soon</span></div><div class="coming-card"><b>☕ NEARBY</b><span>Information coming soon</span></div></div>`;d.classList.add('open')}
function renderChoices(){const g=document.querySelector('#choice-results');if(!g)return;const picks={hike:['Kinder Scout','Helvellyn','Mam Tor'],water:['Aira Force','Buttermere','Rydal Water'],quiet:['Kielder Forest','Buttermere','Dovedale'],photo:['Three Cliffs Bay','Stanage Edge','Glenfinnan'],easy:['Rydal Water','Castlerigg Stone Circle','Dovedale'],weekend:['Lake District','Eryri','Scottish Highlands']};document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(z=>z.classList.remove('active'));b.classList.add('active');const names=picks[b.dataset.choice]||picks.hike;g.innerHTML=names.map(n=>{const d=(D.destinations||[]).find(x=>x.name===n);if(d)return `<article class="mini-card"><b>${esc(d.name)}</b><span>${esc(d.tag)} · ${esc(d.area)}</span><small>${esc(d.desc)}</small><button class="text-btn" onclick="openDestination(${JSON.stringify(d.name)})">VIEW →</button></article>`;const p=allPeaks.find(x=>x.name===n);return `<article class="mini-card"><b>${esc(n)}</b><span>${p?esc(p.kind||p.type):'VIREO PICK'}</span><small>${p?esc(p.description):'A place to discover. More information coming soon.'}</small>${p?`<button class="text-btn" onclick='openProfile(${JSON.stringify(p)},${JSON.stringify(p.kind||p.type)})'>VIEW →</button>`:''}</article>`}).join('')})}
function renderNear(){const g=document.querySelector('#near-results');if(!g)return;const first=Object.keys(D.near||{})[0];const paint=city=>{g.innerHTML=(D.near?.[city]||[]).map((n,i)=>{const p=allPeaks.find(x=>x.name===n);return `<article class="near-card"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(n)}</b><small>${p?`${esc(p.kind||p.type)} · ${esc(p.height)}m`:'Discovery area · information coming soon'}</small>${p?`<button class="text-btn" onclick='openProfile(${JSON.stringify(p)},${JSON.stringify(p.kind||p.type)})'>VIEW →</button>`:''}</article>`}).join('')};document.querySelectorAll('.city').forEach(b=>b.onclick=()=>{document.querySelectorAll('.city').forEach(z=>z.classList.remove('active'));b.classList.add('active');paint(b.dataset.city)});paint(first)}
function renderWeekend(){const g=document.querySelector('#weekend-grid');if(!g)return;g.innerHTML=(D.weekends||[]).map((x,i)=>`<article class="weekend"><span class="pill">WEEKEND ESCAPE ${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><div class="plan">${esc(x.plan)}</div><p>${esc(x.desc)}</p><div class="weekend-extra"><b>WHAT THIS COULD BECOME</b><span>Route ideas · places to stay · food stops · weather · packing notes · nearby alternatives</span></div><div class="coming-label">INFORMATION COMING SOON</div></article>`).join('')}
function updatePassport(){const el=document.querySelector('#passport-stats');if(!el)return;el.innerHTML=`<div><b>${logged.length}</b><span>ADVENTURES LOGGED</span></div><div><b>${favourites.length}</b><span>PLACES SAVED</span></div><div><b>${Math.min(logged.length,214)}</b><span>WAINWRIGHTS</span></div><div><b>${Math.min(logged.length,282)}</b><span>MUNROS</span></div>`}
function bootHash(){if(!location.hash)return;const n=decodeURIComponent(location.hash.replace('#peak=',''));const p=allPeaks.find(x=>x.name===n);if(p)openProfile(p,p.kind||p.type||'VIREO')}
document.addEventListener('click',e=>{if(e.target.id==='drawer')closeDrawer()});
renderDestinations();renderChoices();renderNear();renderWeekend();updatePassport();addDirectoryControls();bootHash();
