const D=window.VIREO_DATA;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stars=n=>'★'.repeat(Number(n)||0)+'☆'.repeat(5-(Number(n)||0));
function closeDrawer(){document.querySelector('#drawer')?.classList.remove('open')}
function openProfile(x,label){
 const d=document.querySelector('#drawer'); if(!d)return;
 d.querySelector('.drawer-panel').innerHTML=`<button class="close" onclick="closeDrawer()">CLOSE</button><div class="kicker">${esc(label)}</div><h2>${esc(x.name)}</h2><div class="height">${x.height}m</div><div class="meta"><span>${esc(x.difficulty)}</span><span class="stars">${stars(x.views)}</span>${x.region?`<span>${esc(x.region)}</span>`:''}</div><p class="profile-description">${esc(x.description)}</p><div class="profile-coming"><strong>MORE ABOUT THIS PLACE</strong><span>Information coming soon — real photographs, exact location, parking and route details will be added to this profile.</span></div>`;
 d.classList.add('open');
}
function renderDirectory(items,o){
 const g=document.querySelector(o.grid),s=document.querySelector(o.search),sort=document.querySelector(o.sort),c=document.querySelector(o.count);let q='',m='height';
 function paint(){let a=items.filter(x=>!q||x.name.toLowerCase().includes(q));if(m==='alpha')a.sort((x,y)=>x.name.localeCompare(y.name));else if(m==='low')a.sort((x,y)=>x.height-y.height);else a.sort((x,y)=>y.height-x.height);c.textContent=`${a.length} of ${items.length} shown`;g.innerHTML=a.map(x=>`<button class="peak-card"><span class="rank">${x.height}m</span><span class="peak-name">${esc(x.name)}</span><span class="peak-height">${esc(x.difficulty)}</span><span class="peak-arrow">↗</span></button>`).join('');[...g.children].forEach((e,i)=>e.onclick=()=>openProfile(a[i],o.label))}
 s?.addEventListener('input',e=>{q=e.target.value.toLowerCase();paint()});sort?.addEventListener('change',e=>{m=e.target.value;paint()});paint();
}
function renderDestinations(){const g=document.querySelector('#destinations-grid');if(!g)return;g.innerHTML=D.destinations.map(x=>`<article class="destination-card"><div class="destination-image" style="background-image:url('${x.image}')"><span>PHOTO</span></div><div class="destination-copy"><span class="pill">${esc(x.tag)}</span><h3>${esc(x.name)}</h3><small>${esc(x.area)}</small><p>${esc(x.desc)}</p><div class="coming-label">${esc(x.imageStatus)}</div></div></article>`).join('')}
function renderChoices(){const g=document.querySelector('#choice-results');if(!g)return;const picks={hike:['Kinder Scout','Helvellyn','Mam Tor'],water:['Aira Force','Buttermere','Rydal Water'],quiet:['Kielder Forest','Buttermere','Dovedale'],photo:['Three Cliffs Bay','Stanage Edge','Glenfinnan'],easy:['Rydal Water','Castlerigg Stone Circle','Dovedale'],weekend:['Lake District','Eryri','Scottish Highlands']};document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(z=>z.classList.remove('active'));b.classList.add('active');const names=picks[b.dataset.choice]||picks.hike;g.innerHTML=names.map(n=>{const d=D.destinations.find(x=>x.name===n);return d?`<article class="mini-card"><span class="pill">${esc(d.tag)}</span><b>${esc(d.name)}</b><small>${esc(d.desc)}</small></article>`:`<article class="mini-card"><span class="pill">VIREO</span><b>${esc(n)}</b><small>A place to discover. More information coming soon.</small></article>`}).join('')})}
function renderNear(){const g=document.querySelector('#near-results');if(!g)return;const first=Object.keys(D.near)[0];const paint=city=>{g.innerHTML=(D.near[city]||[]).map((n,i)=>`<article class="near-card"><span>${String(i+1).padStart(2,'0')}</span><b>${esc(n)}</b><small>Discovery area · information coming soon</small></article>`).join('')};document.querySelectorAll('.city').forEach(b=>b.onclick=()=>{document.querySelectorAll('.city').forEach(z=>z.classList.remove('active'));b.classList.add('active');paint(b.dataset.city)});paint(first)}
function renderWeekend(){const g=document.querySelector('#weekend-grid');if(!g)return;g.innerHTML=D.weekends.map(x=>`<article class="weekend"><span class="pill">WEEKEND ESCAPE</span><h3>${esc(x.title)}</h3><div class="plan">${esc(x.plan)}</div><p>${esc(x.desc)}</p><div class="coming-label">INFORMATION COMING SOON</div></article>`).join('')}
document.addEventListener('click',e=>{if(e.target.id==='drawer')closeDrawer()});
renderDestinations();renderChoices();renderNear();renderWeekend();
